### ISSUE TITLE
Repo is missing thumbnail-example.json

### ISSUE THREAD

**Issue by alexhutnik** [jtheiner/LegoBrickClassification#1]
The code example in the readme shows this command:

`blender -b -P dataset/blender/render.py -- -i 9.dat --save ./ --images_per_brick 1 --config thumbnail-example.json`

However, the repo is missing thumbnail-example.json or the readme does not indicate how to make one or what it should contain.

**Comment by jtheiner** [comment]
Meanwhile available since Oct 31, 2019.
